-- ===================================================
--  BASE DE DATOS PARA PROYECTO : Sistema de Gestión de Activos Visuales (VAMS)
--  AUTOR: CARLOS A. MUÑOZ ALVARADO 
-- ===================================================


-- ===================================================
-- 1) TABLAS DE USUARIOS Y ROLES
-- ===================================================

-- Tabla de roles del sistema
CREATE TABLE VMS_ROL (
    RL_IDROL_PK         NUMBER          PRIMARY KEY,
    RL_NOMBRE           VARCHAR2(50)    NOT NULL,
    RL_DESCRIPCION      VARCHAR2(200),
    RL_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    RL_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    RL_CREADOEN         DATE            DEFAULT SYSDATE,
    RL_MODIFICPOR       VARCHAR2(100),
    RL_MODIFICEN        DATE
);

-- Tabla de usuarios del sistema
CREATE TABLE VMS_USUARIO (
    US_IDUSUARIO_PK     NUMBER          PRIMARY KEY,
    RL_IDROL_FK         NUMBER,
    US_NOMBRE           VARCHAR2(100)   NOT NULL,
    US_CORREO           VARCHAR2(100)    NOT NULL UNIQUE,
    US_TELEFONO         VARCHAR2(20),
    US_USUARIO          VARCHAR2(50)    NOT NULL UNIQUE,
    US_CONTRASENA       VARCHAR2(255)   NOT NULL,
    US_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    US_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    US_CREADOEN         DATE            DEFAULT SYSDATE,
    US_MODIFICPOR       VARCHAR2(100),
    US_MODIFICEN        DATE
);

-- Tabla de relación usuario-proyecto (permisos)
CREATE TABLE VMS_USUARIO_PROYECTO (
    UP_ID_PK            NUMBER          PRIMARY KEY,
    US_IDUSUARIO_FK     NUMBER          NOT NULL,
    PR_IDPROYECTO_FK    NUMBER          NOT NULL,
    UP_PERMISO          VARCHAR2(20)    DEFAULT 'LECTURA' NOT NULL, -- LECTURA, ESCRITURA, ADMIN
    UP_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    UP_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    UP_CREADOEN         DATE            DEFAULT SYSDATE,
    UP_MODIFICPOR       VARCHAR2(100),
    UP_MODIFICEN        DATE
);

-- ===================================================
-- 2) TABLAS DE PROYECTOS Y CATEGORÍAS
-- ===================================================

-- Tabla de proyectos (obras/terrenos)
CREATE TABLE VMS_PROYECTO (
    PR_IDPROYECTO_PK    NUMBER          PRIMARY KEY,
    PR_NOMBRE           VARCHAR2(200)   NOT NULL,
    PR_DESCRIPCION      VARCHAR2(500),
    PR_UBICACION        VARCHAR2(200),
    PR_LATITUD          NUMBER,
    PR_LONGITUD         NUMBER,
    PR_FOTO_PORTADA_URL VARCHAR2(500),  -- URL de la foto de portada (almacenada en CDN/sistema de archivos)
    PR_FECHA_INICIO     DATE,
    PR_FECHA_FIN         DATE,
    PR_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    PR_CREADOPOR         VARCHAR2(100)   DEFAULT USER,
    PR_CREADOEN          DATE            DEFAULT SYSDATE,
    PR_MODIFICPOR        VARCHAR2(100),
    PR_MODIFICEN         DATE
);

-- Tabla de categorías (Drones, Sedes, Interiores, Puntos de Control)
CREATE TABLE VMS_CATEGORIA (
    CT_IDCATEGORIA_PK   NUMBER          PRIMARY KEY,
    PR_IDPROYECTO_FK    NUMBER          NOT NULL,
    CT_NOMBRE           VARCHAR2(100)   NOT NULL,
    CT_DESCRIPCION      VARCHAR2(500),
    CT_ICONO            VARCHAR2(50),   -- Nombre del icono (ej: 'drone', 'building', 'interior')
    CT_COLOR            VARCHAR2(20),    -- Color para identificación visual
    CT_ORDEN            NUMBER          DEFAULT 1,
    CT_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    CT_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    CT_CREADOEN         DATE            DEFAULT SYSDATE,
    CT_MODIFICPOR       VARCHAR2(100),
    CT_MODIFICEN        DATE
);

-- ===================================================
-- 3) TABLAS DE ACTIVOS VISUALES Y METADATOS
-- ===================================================

-- Tabla principal de activos visuales (fotos)
CREATE TABLE VMS_ACTIVO_VISUAL (
    AV_IDACTIVO_PK      NUMBER          PRIMARY KEY,
    PR_IDPROYECTO_FK    NUMBER          NOT NULL,
    CT_IDCATEGORIA_FK   NUMBER          NOT NULL,
    US_IDUSUARIO_FK     NUMBER          NOT NULL,
    AV_NOMBRE           VARCHAR2(200),
    AV_DESCRIPCION      VARCHAR2(1000),
    AV_URL              VARCHAR2(500)   NOT NULL, -- URL del archivo (almacenado en CDN/sistema de archivos)
    AV_FILENAME          VARCHAR2(256),  -- Nombre original del archivo
    AV_MIMETYPE          VARCHAR2(256),  -- Tipo MIME del archivo
    AV_TAMANIO           NUMBER,         -- Tamaño en bytes
    AV_FECHA_CAPTURA     DATE,           -- Fecha de captura (extraída de EXIF)
    AV_FECHA_CARGA       DATE            DEFAULT SYSDATE,
    AV_LATITUD           NUMBER,         -- Coordenadas GPS
    AV_LONGITUD          NUMBER,
    AV_ALTURA            NUMBER,         -- Altura del drone (si aplica)
    AV_ANGULO_CAMARA     NUMBER,         -- Ángulo de la cámara
    AV_ACTIVO            VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    AV_CREADOPOR         VARCHAR2(100)   DEFAULT USER,
    AV_CREADOEN          DATE            DEFAULT SYSDATE,
    AV_MODIFICPOR        VARCHAR2(100),
    AV_MODIFICEN         DATE,
    AV_LASTUPDATE         DATE
);

-- Tabla de metadatos EXIF extendidos
CREATE TABLE VMS_METADATO_EXIF (
    ME_IDMETADATO_PK    NUMBER          PRIMARY KEY,
    AV_IDACTIVO_FK      NUMBER          NOT NULL,
    ME_CAMARA           VARCHAR2(200),
    ME_LENTE            VARCHAR2(200),
    ME_ISO              NUMBER,
    ME_VELOCIDAD        VARCHAR2(50),   -- Velocidad de obturación
    ME_APERTURA         VARCHAR2(50),   -- Apertura del diafragma
    ME_RESOLUCION_X     NUMBER,
    ME_RESOLUCION_Y     NUMBER,
    ME_ORIENTACION      NUMBER,
    ME_SOFTWARE         VARCHAR2(200),
    ME_DATOS_RAW        CLOB,           -- JSON con todos los metadatos EXIF
    ME_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    ME_CREADOEN         DATE            DEFAULT SYSDATE,
    ME_MODIFICPOR       VARCHAR2(100),
    ME_MODIFICEN        DATE
);

-- ===================================================
-- 4) TABLAS DE COMPARACIONES Y CRONOLOGÍA
-- ===================================================

-- Tabla de comparaciones (Antes/Después)
CREATE TABLE VMS_COMPARACION (
    CO_IDCOMPARACION_PK NUMBER          PRIMARY KEY,
    PR_IDPROYECTO_FK    NUMBER          NOT NULL,
    CT_IDCATEGORIA_FK   NUMBER          NOT NULL,
    AV_IDACTIVO_ANTES_FK NUMBER         NOT NULL, -- Foto "antes"
    AV_IDACTIVO_DESPUES_FK NUMBER       NOT NULL, -- Foto "después"
    CO_NOMBRE           VARCHAR2(200),
    CO_DESCRIPCION      VARCHAR2(1000),
    CO_FECHA_CREACION   DATE            DEFAULT SYSDATE,
    US_IDUSUARIO_FK     NUMBER          NOT NULL,
    CO_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    CO_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    CO_CREADOEN         DATE            DEFAULT SYSDATE,
    CO_MODIFICPOR       VARCHAR2(100),
    CO_MODIFICEN        DATE
);

-- ===================================================
-- 5) TABLAS DE GESTIÓN Y CONFIGURACIÓN
-- ===================================================

-- Tabla de log de cargas de archivos
CREATE TABLE VMS_CARGA_ARCHIVO (
    CA_IDCARGA_PK       NUMBER          PRIMARY KEY,
    US_IDUSUARIO_FK     NUMBER          NOT NULL,
    PR_IDPROYECTO_FK    NUMBER          NOT NULL,
    CT_IDCATEGORIA_FK   NUMBER          NOT NULL,
    CA_CANTIDAD_ARCHIVOS NUMBER         DEFAULT 0,
    CA_TAMANIO_TOTAL    NUMBER,         -- Tamaño total en bytes
    CA_FECHA_CARGA      DATE            DEFAULT SYSDATE,
    CA_ESTADO           VARCHAR2(20)    DEFAULT 'COMPLETADA', -- COMPLETADA, ERROR, PROCESANDO
    CA_MENSAJE_ERROR    VARCHAR2(1000),
    CA_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    CA_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    CA_CREADOEN         DATE            DEFAULT SYSDATE,
    CA_MODIFICPOR       VARCHAR2(100),
    CA_MODIFICEN        DATE
);

-- Tabla de configuración del sistema
CREATE TABLE VMS_CONFIGURACION (
    CF_IDCONFIG_PK      NUMBER          PRIMARY KEY,
    CF_CLAVE            VARCHAR2(100)    NOT NULL UNIQUE,
    CF_VALOR            VARCHAR2(500),
    CF_DESCRIPCION      VARCHAR2(500),
    CF_TIPO             VARCHAR2(50),    -- STRING, NUMBER, BOOLEAN, JSON
    CF_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    CF_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    CF_CREADOEN         DATE            DEFAULT SYSDATE,
    CF_MODIFICPOR       VARCHAR2(100),
    CF_MODIFICEN        DATE
);

-- ===================================================
-- 6) TABLAS DE ALMACENAMIENTO Y ESTADÍSTICAS
-- ===================================================

-- Tabla de estadísticas de almacenamiento por proyecto
CREATE TABLE VMS_ESTADISTICA_ALMACENAMIENTO (
    EA_IDESTADISTICA_PK NUMBER          PRIMARY KEY,
    PR_IDPROYECTO_FK    NUMBER          NOT NULL,
    EA_FECHA            DATE            DEFAULT SYSDATE,
    EA_TOTAL_ARCHIVOS   NUMBER          DEFAULT 0,
    EA_TAMANIO_TOTAL    NUMBER          DEFAULT 0, -- En bytes
    EA_ARCHIVOS_MES     NUMBER          DEFAULT 0, -- Archivos subidos en el mes
    EA_TAMANIO_MES      NUMBER          DEFAULT 0, -- Tamaño subido en el mes
    EA_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL,
    EA_CREADOPOR        VARCHAR2(100)   DEFAULT USER,
    EA_CREADOEN         DATE            DEFAULT SYSDATE,
    EA_MODIFICPOR       VARCHAR2(100),
    EA_MODIFICEN        DATE
);

-- ===================================================
-- 7) SECUENCIAS PARA PRIMARY KEYS
-- ===================================================

CREATE SEQUENCE SEQ_VMS_ROL MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_USUARIO MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_USUARIO_PROYECTO MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_PROYECTO MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_CATEGORIA MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_ACTIVO_VISUAL MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_METADATO_EXIF MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_COMPARACION MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_CARGA_ARCHIVO MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_CONFIGURACION MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_VMS_ESTADISTICA_ALMACENAMIENTO MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

-- ===================================================
-- 8) CONSTRAINTS
-- ===================================================

-- Constraints para VMS_USUARIO
ALTER TABLE VMS_USUARIO ADD CONSTRAINT FK_VMS_US_ROL FOREIGN KEY (RL_IDROL_FK) REFERENCES VMS_ROL(RL_IDROL_PK);

-- Constraints para VMS_USUARIO_PROYECTO
ALTER TABLE VMS_USUARIO_PROYECTO ADD CONSTRAINT FK_VMS_UP_USUARIO FOREIGN KEY (US_IDUSUARIO_FK) REFERENCES VMS_USUARIO(US_IDUSUARIO_PK);
ALTER TABLE VMS_USUARIO_PROYECTO ADD CONSTRAINT FK_VMS_UP_PROYECTO FOREIGN KEY (PR_IDPROYECTO_FK) REFERENCES VMS_PROYECTO(PR_IDPROYECTO_PK);
ALTER TABLE VMS_USUARIO_PROYECTO ADD CONSTRAINT UK_VMS_UP_USUARIO_PROYECTO UNIQUE (US_IDUSUARIO_FK, PR_IDPROYECTO_FK);

-- Constraints para VMS_CATEGORIA
ALTER TABLE VMS_CATEGORIA ADD CONSTRAINT FK_VMS_CT_PROYECTO FOREIGN KEY (PR_IDPROYECTO_FK) REFERENCES VMS_PROYECTO(PR_IDPROYECTO_PK);

-- Constraints para VMS_ACTIVO_VISUAL
ALTER TABLE VMS_ACTIVO_VISUAL ADD CONSTRAINT FK_VMS_AV_PROYECTO FOREIGN KEY (PR_IDPROYECTO_FK) REFERENCES VMS_PROYECTO(PR_IDPROYECTO_PK);
ALTER TABLE VMS_ACTIVO_VISUAL ADD CONSTRAINT FK_VMS_AV_CATEGORIA FOREIGN KEY (CT_IDCATEGORIA_FK) REFERENCES VMS_CATEGORIA(CT_IDCATEGORIA_PK);
ALTER TABLE VMS_ACTIVO_VISUAL ADD CONSTRAINT FK_VMS_AV_USUARIO FOREIGN KEY (US_IDUSUARIO_FK) REFERENCES VMS_USUARIO(US_IDUSUARIO_PK);

-- Constraints para VMS_METADATO_EXIF
ALTER TABLE VMS_METADATO_EXIF ADD CONSTRAINT FK_VMS_ME_ACTIVO FOREIGN KEY (AV_IDACTIVO_FK) REFERENCES VMS_ACTIVO_VISUAL(AV_IDACTIVO_PK);
ALTER TABLE VMS_METADATO_EXIF ADD CONSTRAINT UK_VMS_ME_ACTIVO UNIQUE (AV_IDACTIVO_FK);

-- Constraints para VMS_COMPARACION
ALTER TABLE VMS_COMPARACION ADD CONSTRAINT FK_VMS_CO_PROYECTO FOREIGN KEY (PR_IDPROYECTO_FK) REFERENCES VMS_PROYECTO(PR_IDPROYECTO_PK);
ALTER TABLE VMS_COMPARACION ADD CONSTRAINT FK_VMS_CO_CATEGORIA FOREIGN KEY (CT_IDCATEGORIA_FK) REFERENCES VMS_CATEGORIA(CT_IDCATEGORIA_PK);
ALTER TABLE VMS_COMPARACION ADD CONSTRAINT FK_VMS_CO_ACTIVO_ANTES FOREIGN KEY (AV_IDACTIVO_ANTES_FK) REFERENCES VMS_ACTIVO_VISUAL(AV_IDACTIVO_PK);
ALTER TABLE VMS_COMPARACION ADD CONSTRAINT FK_VMS_CO_ACTIVO_DESPUES FOREIGN KEY (AV_IDACTIVO_DESPUES_FK) REFERENCES VMS_ACTIVO_VISUAL(AV_IDACTIVO_PK);
ALTER TABLE VMS_COMPARACION ADD CONSTRAINT FK_VMS_CO_USUARIO FOREIGN KEY (US_IDUSUARIO_FK) REFERENCES VMS_USUARIO(US_IDUSUARIO_PK);
ALTER TABLE VMS_COMPARACION ADD CONSTRAINT CHK_VMS_CO_ACTIVOS_DIFERENTES CHECK (AV_IDACTIVO_ANTES_FK != AV_IDACTIVO_DESPUES_FK);

-- Constraints para VMS_CARGA_ARCHIVO
ALTER TABLE VMS_CARGA_ARCHIVO ADD CONSTRAINT FK_VMS_CA_USUARIO FOREIGN KEY (US_IDUSUARIO_FK) REFERENCES VMS_USUARIO(US_IDUSUARIO_PK);
ALTER TABLE VMS_CARGA_ARCHIVO ADD CONSTRAINT FK_VMS_CA_PROYECTO FOREIGN KEY (PR_IDPROYECTO_FK) REFERENCES VMS_PROYECTO(PR_IDPROYECTO_PK);
ALTER TABLE VMS_CARGA_ARCHIVO ADD CONSTRAINT FK_VMS_CA_CATEGORIA FOREIGN KEY (CT_IDCATEGORIA_FK) REFERENCES VMS_CATEGORIA(CT_IDCATEGORIA_PK);

-- Constraints para VMS_ESTADISTICA_ALMACENAMIENTO
ALTER TABLE VMS_ESTADISTICA_ALMACENAMIENTO ADD CONSTRAINT FK_VMS_EA_PROYECTO FOREIGN KEY (PR_IDPROYECTO_FK) REFERENCES VMS_PROYECTO(PR_IDPROYECTO_PK);

-- ===================================================
-- 9) CHECKS DE VALIDACIÓN
-- ===================================================

-- Checks para campos SI/NO
ALTER TABLE VMS_ROL ADD CONSTRAINT CHK_VMS_RL_ACTIVO CHECK (RL_ACTIVO IN ('SI', 'NO'));
ALTER TABLE VMS_USUARIO ADD CONSTRAINT CHK_VMS_US_ACTIVO CHECK (US_ACTIVO IN ('SI', 'NO'));
ALTER TABLE VMS_USUARIO_PROYECTO ADD CONSTRAINT CHK_VMS_UP_ACTIVO CHECK (UP_ACTIVO IN ('SI', 'NO'));
ALTER TABLE VMS_USUARIO_PROYECTO ADD CONSTRAINT CHK_VMS_UP_PERMISO CHECK (UP_PERMISO IN ('LECTURA', 'ESCRITURA', 'ADMIN'));

-- Checks para proyectos
ALTER TABLE VMS_PROYECTO ADD CONSTRAINT CHK_VMS_PR_ACTIVO CHECK (PR_ACTIVO IN ('SI', 'NO'));

-- Checks para categorías
ALTER TABLE VMS_CATEGORIA ADD CONSTRAINT CHK_VMS_CT_ACTIVO CHECK (CT_ACTIVO IN ('SI', 'NO'));

-- Checks para activos visuales
ALTER TABLE VMS_ACTIVO_VISUAL ADD CONSTRAINT CHK_VMS_AV_ACTIVO CHECK (AV_ACTIVO IN ('SI', 'NO'));

-- Checks para comparaciones
ALTER TABLE VMS_COMPARACION ADD CONSTRAINT CHK_VMS_CO_ACTIVO CHECK (CO_ACTIVO IN ('SI', 'NO'));

-- Checks para carga de archivos
ALTER TABLE VMS_CARGA_ARCHIVO ADD CONSTRAINT CHK_VMS_CA_ACTIVO CHECK (CA_ACTIVO IN ('SI', 'NO'));
ALTER TABLE VMS_CARGA_ARCHIVO ADD CONSTRAINT CHK_VMS_CA_ESTADO CHECK (CA_ESTADO IN ('COMPLETADA', 'ERROR', 'PROCESANDO'));

-- Checks para configuración
ALTER TABLE VMS_CONFIGURACION ADD CONSTRAINT CHK_VMS_CF_ACTIVO CHECK (CF_ACTIVO IN ('SI', 'NO'));

-- Checks para estadísticas
ALTER TABLE VMS_ESTADISTICA_ALMACENAMIENTO ADD CONSTRAINT CHK_VMS_EA_ACTIVO CHECK (EA_ACTIVO IN ('SI', 'NO'));

-- ===================================================
-- 10) DATOS INICIALES
-- ===================================================

-- Insertar roles básicos del sistema
INSERT INTO VMS_ROL (RL_IDROL_PK, RL_NOMBRE, RL_DESCRIPCION) VALUES (1, 'ADMINISTRADOR', 'Acceso completo al sistema, gestión de proyectos y usuarios');
INSERT INTO VMS_ROL (RL_IDROL_PK, RL_NOMBRE, RL_DESCRIPCION) VALUES (2, 'GESTOR PROYECTO', 'Gestión completa de proyectos asignados, carga de archivos y comparaciones');
INSERT INTO VMS_ROL (RL_IDROL_PK, RL_NOMBRE, RL_DESCRIPCION) VALUES (3, 'VISUALIZADOR', 'Solo lectura, visualización de proyectos y activos visuales');
INSERT INTO VMS_ROL (RL_IDROL_PK, RL_NOMBRE, RL_DESCRIPCION) VALUES (4, 'CARGA ARCHIVOS', 'Permiso para cargar archivos en proyectos asignados');

-- Insertar categorías predefinidas (se asociarán a proyectos específicos)
-- Nota: Estas categorías se crearán dinámicamente por proyecto, pero aquí están los tipos base
-- Los iconos sugeridos: 'drone', 'building', 'interior', 'map-pin'

-- Configuración inicial del sistema
INSERT INTO VMS_CONFIGURACION (CF_IDCONFIG_PK, CF_CLAVE, CF_VALOR, CF_DESCRIPCION, CF_TIPO) 
VALUES (1, 'MAX_TAMANIO_ARCHIVO', '52428800', 'Tamaño máximo de archivo en bytes (50MB)', 'NUMBER');

INSERT INTO VMS_CONFIGURACION (CF_IDCONFIG_PK, CF_CLAVE, CF_VALOR, CF_DESCRIPCION, CF_TIPO) 
VALUES (2, 'FORMATOS_PERMITIDOS', 'JPG,JPEG,PNG,HEIC,RAW', 'Formatos de imagen permitidos separados por coma', 'STRING');

INSERT INTO VMS_CONFIGURACION (CF_IDCONFIG_PK, CF_CLAVE, CF_VALOR, CF_DESCRIPCION, CF_TIPO) 
VALUES (3, 'CDN_HABILITADO', 'SI', 'Indica si el CDN está habilitado para entrega de contenido', 'STRING');

INSERT INTO VMS_CONFIGURACION (CF_IDCONFIG_PK, CF_CLAVE, CF_VALOR, CF_DESCRIPCION, CF_TIPO) 
VALUES (5, 'CDN_BASE_URL', '', 'URL base del CDN o sistema de almacenamiento de archivos', 'STRING');

INSERT INTO VMS_CONFIGURACION (CF_IDCONFIG_PK, CF_CLAVE, CF_VALOR, CF_DESCRIPCION, CF_TIPO) 
VALUES (4, 'LAZY_LOADING', 'SI', 'Habilita la carga diferida de imágenes', 'STRING');

COMMIT;

-- ===================================================
-- 11) TRIGGERS
-- ===================================================

CREATE OR REPLACE TRIGGER "TRG_VMS_ROL"
BEFORE INSERT OR UPDATE ON "VMS_ROL"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.RL_IDROL_PK IS NULL THEN
          SELECT SEQ_VMS_ROL.NEXTVAL INTO :NEW.RL_IDROL_PK FROM DUAL;
       END IF;
       :NEW.RL_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.RL_CREADOEN:= SYSDATE;
    END IF;
    IF UPDATING THEN
       :NEW.RL_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.RL_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_USUARIO"
BEFORE INSERT OR UPDATE ON "VMS_USUARIO"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.US_IDUSUARIO_PK IS NULL THEN
          SELECT SEQ_VMS_USUARIO.NEXTVAL INTO :NEW.US_IDUSUARIO_PK FROM DUAL;
       END IF;
       :NEW.US_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.US_CREADOEN:= SYSDATE;
    END IF;
    IF UPDATING THEN
       :NEW.US_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.US_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_USUARIO_PROYECTO"
BEFORE INSERT OR UPDATE ON "VMS_USUARIO_PROYECTO"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.UP_ID_PK IS NULL THEN
          SELECT SEQ_VMS_USUARIO_PROYECTO.NEXTVAL INTO :NEW.UP_ID_PK FROM DUAL;
       END IF;
       :NEW.UP_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.UP_CREADOEN:= SYSDATE;
    END IF;
    IF UPDATING THEN
       :NEW.UP_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.UP_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_PROYECTO"
BEFORE INSERT OR UPDATE ON "VMS_PROYECTO"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.PR_IDPROYECTO_PK IS NULL THEN
          SELECT SEQ_VMS_PROYECTO.NEXTVAL INTO :NEW.PR_IDPROYECTO_PK FROM DUAL;
       END IF;
       :NEW.PR_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.PR_CREADOEN:= SYSDATE;
       IF :NEW.PR_FECHA_FIN IS NOT NULL AND :NEW.PR_FECHA_FIN < :NEW.PR_FECHA_INICIO THEN
          RAISE_APPLICATION_ERROR(-20001, 'La fecha de fin no puede ser anterior a la fecha de inicio');
       END IF;
    END IF;
    IF UPDATING THEN
       :NEW.PR_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.PR_MODIFICEN:= SYSDATE;
       IF :NEW.PR_FECHA_FIN IS NOT NULL AND :NEW.PR_FECHA_FIN < :NEW.PR_FECHA_INICIO THEN
          RAISE_APPLICATION_ERROR(-20001, 'La fecha de fin no puede ser anterior a la fecha de inicio');
       END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_CATEGORIA"
BEFORE INSERT OR UPDATE ON "VMS_CATEGORIA"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.CT_IDCATEGORIA_PK IS NULL THEN
          SELECT SEQ_VMS_CATEGORIA.NEXTVAL INTO :NEW.CT_IDCATEGORIA_PK FROM DUAL;
       END IF;
       :NEW.CT_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.CT_CREADOEN:= SYSDATE;
    END IF;
    IF UPDATING THEN
       :NEW.CT_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.CT_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_ACTIVO_VISUAL"
BEFORE INSERT OR UPDATE ON "VMS_ACTIVO_VISUAL"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.AV_IDACTIVO_PK IS NULL THEN
          SELECT SEQ_VMS_ACTIVO_VISUAL.NEXTVAL INTO :NEW.AV_IDACTIVO_PK FROM DUAL;
       END IF;
       :NEW.AV_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.AV_CREADOEN:= SYSDATE;
       :NEW.AV_FECHA_CARGA:= SYSDATE;
       IF :NEW.AV_FECHA_CAPTURA IS NULL THEN
          :NEW.AV_FECHA_CAPTURA:= SYSDATE;
       END IF;
    END IF;
    IF UPDATING THEN
       :NEW.AV_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.AV_MODIFICEN:= SYSDATE;
       :NEW.AV_LASTUPDATE:= SYSDATE;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_METADATO_EXIF"
BEFORE INSERT OR UPDATE ON "VMS_METADATO_EXIF"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.ME_IDMETADATO_PK IS NULL THEN
          SELECT SEQ_VMS_METADATO_EXIF.NEXTVAL INTO :NEW.ME_IDMETADATO_PK FROM DUAL;
       END IF;
       :NEW.ME_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.ME_CREADOEN:= SYSDATE;
    END IF;
    IF UPDATING THEN
       :NEW.ME_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.ME_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_COMPARACION"
BEFORE INSERT OR UPDATE ON "VMS_COMPARACION"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.CO_IDCOMPARACION_PK IS NULL THEN
          SELECT SEQ_VMS_COMPARACION.NEXTVAL INTO :NEW.CO_IDCOMPARACION_PK FROM DUAL;
       END IF;
       :NEW.CO_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.CO_CREADOEN:= SYSDATE;
       :NEW.CO_FECHA_CREACION:= SYSDATE;
    END IF;
    IF UPDATING THEN
       :NEW.CO_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.CO_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_CARGA_ARCHIVO"
BEFORE INSERT OR UPDATE ON "VMS_CARGA_ARCHIVO"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.CA_IDCARGA_PK IS NULL THEN
          SELECT SEQ_VMS_CARGA_ARCHIVO.NEXTVAL INTO :NEW.CA_IDCARGA_PK FROM DUAL;
       END IF;
       :NEW.CA_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.CA_CREADOEN:= SYSDATE;
       :NEW.CA_FECHA_CARGA:= SYSDATE;
    END IF;
    IF UPDATING THEN
       :NEW.CA_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.CA_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_CONFIGURACION"
BEFORE INSERT OR UPDATE ON "VMS_CONFIGURACION"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.CF_IDCONFIG_PK IS NULL THEN
          SELECT SEQ_VMS_CONFIGURACION.NEXTVAL INTO :NEW.CF_IDCONFIG_PK FROM DUAL;
       END IF;
       :NEW.CF_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.CF_CREADOEN:= SYSDATE;
    END IF;
    IF UPDATING THEN
       :NEW.CF_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.CF_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "TRG_VMS_ESTADISTICA_ALMACENAMIENTO"
BEFORE INSERT OR UPDATE ON "VMS_ESTADISTICA_ALMACENAMIENTO"
REFERENCING FOR EACH ROW
BEGIN
    IF INSERTING THEN
       IF :NEW.EA_IDESTADISTICA_PK IS NULL THEN
          SELECT SEQ_VMS_ESTADISTICA_ALMACENAMIENTO.NEXTVAL INTO :NEW.EA_IDESTADISTICA_PK FROM DUAL;
       END IF;
       :NEW.EA_CREADOPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.EA_CREADOEN:= SYSDATE;
       IF :NEW.EA_FECHA IS NULL THEN
          :NEW.EA_FECHA:= SYSDATE;
       END IF;
    END IF;
    IF UPDATING THEN
       :NEW.EA_MODIFICPOR:= NVL(HTMLDB_CUSTOM_AUTH.GET_USERNAME,USER);
       :NEW.EA_MODIFICEN:= SYSDATE; 
    END IF;
END;
/

COMMIT;

-- ===================================================
-- 12) VISTAS ÚTILES
-- ===================================================

-- Vista de proyectos con información resumida
CREATE OR REPLACE VIEW V_PROYECTO_RESUMEN AS
SELECT 
    p.PR_IDPROYECTO_PK,
    p.PR_NOMBRE,
    p.PR_UBICACION,
    p.PR_FOTO_PORTADA_URL,
    p.PR_FECHA_INICIO,
    p.PR_FECHA_FIN,
    p.PR_ACTIVO,
    COUNT(DISTINCT av.AV_IDACTIVO_PK) AS TOTAL_ACTIVOS,
    COUNT(DISTINCT ct.CT_IDCATEGORIA_PK) AS TOTAL_CATEGORIAS,
    MAX(av.AV_FECHA_CARGA) AS ULTIMA_ACTUALIZACION
FROM VMS_PROYECTO p,
     VMS_CATEGORIA ct,
     VMS_ACTIVO_VISUAL av
WHERE p.PR_ACTIVO = 'SI'
  AND p.PR_IDPROYECTO_PK = ct.PR_IDPROYECTO_FK (+)
  AND (ct.CT_ACTIVO = 'SI' OR ct.CT_ACTIVO IS NULL)
  AND p.PR_IDPROYECTO_PK = av.PR_IDPROYECTO_FK (+)
  AND (av.AV_ACTIVO = 'SI' OR av.AV_ACTIVO IS NULL)
GROUP BY p.PR_IDPROYECTO_PK, p.PR_NOMBRE, p.PR_UBICACION, p.PR_FOTO_PORTADA_URL, p.PR_FECHA_INICIO, p.PR_FECHA_FIN, p.PR_ACTIVO;

-- Vista de activos visuales con información completa
CREATE OR REPLACE VIEW V_ACTIVO_VISUAL_COMPLETO AS
SELECT 
    av.AV_IDACTIVO_PK,
    av.PR_IDPROYECTO_FK,
    p.PR_NOMBRE AS PROYECTO_NOMBRE,
    av.CT_IDCATEGORIA_FK,
    ct.CT_NOMBRE AS CATEGORIA_NOMBRE,
    ct.CT_ICONO AS CATEGORIA_ICONO,
    av.US_IDUSUARIO_FK,
    u.US_NOMBRE AS USUARIO_NOMBRE,
    av.AV_NOMBRE,
    av.AV_DESCRIPCION,
    av.AV_URL,
    av.AV_FILENAME,
    av.AV_MIMETYPE,
    av.AV_TAMANIO,
    av.AV_FECHA_CAPTURA,
    av.AV_FECHA_CARGA,
    av.AV_LATITUD,
    av.AV_LONGITUD,
    av.AV_ALTURA,
    av.AV_ANGULO_CAMARA,
    me.ME_CAMARA,
    me.ME_LENTE,
    me.ME_ISO,
    me.ME_RESOLUCION_X,
    me.ME_RESOLUCION_Y
FROM VMS_ACTIVO_VISUAL av,
     VMS_PROYECTO p,
     VMS_CATEGORIA ct,
     VMS_USUARIO u,
     VMS_METADATO_EXIF me
WHERE av.AV_ACTIVO = 'SI'
  AND p.PR_ACTIVO = 'SI'
  AND ct.CT_ACTIVO = 'SI'
  AND av.PR_IDPROYECTO_FK = p.PR_IDPROYECTO_PK
  AND av.CT_IDCATEGORIA_FK = ct.CT_IDCATEGORIA_PK
  AND av.US_IDUSUARIO_FK = u.US_IDUSUARIO_PK
  AND av.AV_IDACTIVO_PK = me.AV_IDACTIVO_FK (+);

-- Vista de comparaciones con información de activos
CREATE OR REPLACE VIEW V_COMPARACION_COMPLETA AS
SELECT 
    c.CO_IDCOMPARACION_PK,
    c.PR_IDPROYECTO_FK,
    p.PR_NOMBRE AS PROYECTO_NOMBRE,
    c.CT_IDCATEGORIA_FK,
    ct.CT_NOMBRE AS CATEGORIA_NOMBRE,
    c.AV_IDACTIVO_ANTES_FK,
    av_antes.AV_URL AS URL_ANTES,
    av_antes.AV_FILENAME AS ARCHIVO_ANTES,
    av_antes.AV_FECHA_CAPTURA AS FECHA_ANTES,
    c.AV_IDACTIVO_DESPUES_FK,
    av_despues.AV_URL AS URL_DESPUES,
    av_despues.AV_FILENAME AS ARCHIVO_DESPUES,
    av_despues.AV_FECHA_CAPTURA AS FECHA_DESPUES,
    c.CO_NOMBRE,
    c.CO_DESCRIPCION,
    c.CO_FECHA_CREACION,
    c.US_IDUSUARIO_FK,
    u.US_NOMBRE AS USUARIO_NOMBRE
FROM VMS_COMPARACION c,
     VMS_PROYECTO p,
     VMS_CATEGORIA ct,
     VMS_ACTIVO_VISUAL av_antes,
     VMS_ACTIVO_VISUAL av_despues,
     VMS_USUARIO u
WHERE c.CO_ACTIVO = 'SI'
  AND c.PR_IDPROYECTO_FK = p.PR_IDPROYECTO_PK
  AND c.CT_IDCATEGORIA_FK = ct.CT_IDCATEGORIA_PK
  AND c.AV_IDACTIVO_ANTES_FK = av_antes.AV_IDACTIVO_PK
  AND c.AV_IDACTIVO_DESPUES_FK = av_despues.AV_IDACTIVO_PK
  AND c.US_IDUSUARIO_FK = u.US_IDUSUARIO_PK;

COMMIT;





-- ===================================================
-- 13) TABLA DE TOKENS DE API (OPCIÓN 2: SIMPLE Y CORTO)
-- ===================================================

CREATE TABLE VMS_TOKEN_API (
    TA_IDTOKEN_PK       NUMBER          PRIMARY KEY,
    US_IDUSUARIO_FK     NUMBER          NOT NULL,
    TA_TOKEN            VARCHAR2(32)   NOT NULL UNIQUE,
    TA_FECHA_CREACION   DATE            DEFAULT SYSDATE,
    TA_FECHA_EXPIRACION DATE            NOT NULL,
    TA_ACTIVO           VARCHAR2(2)     DEFAULT 'SI' NOT NULL
);

-- Secuencia para tokens
CREATE SEQUENCE SEQ_VMS_TOKEN_API MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

-- Constraints
ALTER TABLE VMS_TOKEN_API ADD CONSTRAINT FK_VMS_TA_USUARIO FOREIGN KEY (US_IDUSUARIO_FK) REFERENCES VMS_USUARIO(US_IDUSUARIO_PK);
ALTER TABLE VMS_TOKEN_API ADD CONSTRAINT CHK_VMS_TA_ACTIVO CHECK (TA_ACTIVO IN ('SI', 'NO'));

-- Índice para búsqueda rápida por token
CREATE INDEX IDX_VMS_TA_TOKEN ON VMS_TOKEN_API(TA_TOKEN);

-- ===================================================
-- 14) FUNCIONES DE AUTENTICACIÓN Y TOKENS
-- ===================================================

CREATE OR REPLACE FUNCTION VMS_AUTENTICAR_USUARIO (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2
) RETURN NUMBER
IS
    v_dummy NUMBER;
    v_usuario_id NUMBER;
BEGIN
    -- Intentamos encontrar un usuario activo con credenciales correctas
    SELECT US_IDUSUARIO_PK
    INTO   v_usuario_id
    FROM   VMS_USUARIO
    WHERE  UPPER(US_USUARIO) = UPPER(TRIM(p_username))
      AND  US_CONTRASENA = STANDARD_HASH(TRIM(p_password), 'MD5')
      AND  US_ACTIVO = 'SI';

    --  retornamos el ID del usuario
    RETURN v_usuario_id;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;                
    WHEN TOO_MANY_ROWS THEN
        RETURN 0;                 
    WHEN OTHERS THEN
        RETURN 0;                 
END VMS_AUTENTICAR_USUARIO;
/

-- Función para generar token simple (32 caracteres)
CREATE OR REPLACE FUNCTION VMS_GENERAR_TOKEN (
    p_usuario_id IN NUMBER,
    p_horas_validez IN NUMBER DEFAULT 24
) RETURN VARCHAR2
IS
    v_token VARCHAR2(32);
    v_token_id NUMBER;
    v_string VARCHAR2(200);
BEGIN
    -- Generar string único: usuario_id + timestamp + random
    v_string := p_usuario_id || '_' || 
                TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '_' || 
                DBMS_RANDOM.STRING('X', 16);
    
    -- Generar MD5 hash (32 caracteres)
    SELECT SUBSTR(STANDARD_HASH(v_string, 'MD5'), 1, 32)
    INTO v_token
    FROM DUAL;
    
    -- Obtener siguiente ID
    SELECT SEQ_VMS_TOKEN_API.NEXTVAL INTO v_token_id FROM DUAL;
    
    -- Invalidar tokens anteriores del usuario
    UPDATE VMS_TOKEN_API
    SET TA_ACTIVO = 'NO'
    WHERE US_IDUSUARIO_FK = p_usuario_id
      AND TA_ACTIVO = 'SI';
    
    -- Insertar nuevo token
    INSERT INTO VMS_TOKEN_API (
        TA_IDTOKEN_PK,
        US_IDUSUARIO_FK,
        TA_TOKEN,
        TA_FECHA_CREACION,
        TA_FECHA_EXPIRACION,
        TA_ACTIVO
    ) VALUES (
        v_token_id,
        p_usuario_id,
        v_token,
        SYSDATE,
        SYSDATE + (p_horas_validez / 24),
        'SI'
    );
    
    COMMIT;
    
    RETURN v_token;
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN NULL;
END VMS_GENERAR_TOKEN;
/

-- Función para validar token
CREATE OR REPLACE FUNCTION VMS_VALIDAR_TOKEN (
    p_token IN VARCHAR2
) RETURN NUMBER
IS
    v_usuario_id NUMBER;
BEGIN
    -- Buscar token válido y activo
    SELECT US_IDUSUARIO_FK
    INTO v_usuario_id
    FROM VMS_TOKEN_API
    WHERE TA_TOKEN = p_token
      AND TA_ACTIVO = 'SI'
      AND TA_FECHA_EXPIRACION > SYSDATE
      AND ROWNUM = 1;
    
    RETURN v_usuario_id;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RETURN 0;
END VMS_VALIDAR_TOKEN;
/

-- Función para invalidar token (logout)
CREATE OR REPLACE FUNCTION VMS_INVALIDAR_TOKEN (
    p_token IN VARCHAR2
) RETURN VARCHAR2
IS
BEGIN
    UPDATE VMS_TOKEN_API
    SET TA_ACTIVO = 'NO'
    WHERE TA_TOKEN = p_token;
    
    COMMIT;
    
    RETURN 'SI';
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'NO';
END VMS_INVALIDAR_TOKEN;
/

COMMIT;