
-- Generated by ORDS REST Data Services para VAMS
-- Schema: SATOR  Date: 2026-01-06
-- Sistema de Gestión de Activos Visuales (VAMS)
--
        
BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'vams/',
      p_base_path      => '/vams/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'vams/',
      p_pattern        => 'auth/login',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'auth/login',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  L_PO  BLOB := :body;
  V_USER_ID NUMBER;
  V_USER_NOMBRE VARCHAR2(100);
  V_USER_CORREO VARCHAR2(100);
  V_USER_USUARIO VARCHAR2(50);
  V_ROL_ID NUMBER;
  V_ROL_NOMBRE VARCHAR2(50);
  V_TOKEN VARCHAR2(32);
  V_TOKEN_ID NUMBER;
  V_STRING VARCHAR2(200);
  V_USERNAME VARCHAR2(50);
  V_PASSWORD VARCHAR2(255);
BEGIN
    -- Extraer username y password del JSON
    SELECT jt.username, jt.password
    INTO V_USERNAME, V_PASSWORD
    FROM JSON_TABLE(L_PO FORMAT JSON, ''$''
             COLUMNS (
               username VARCHAR2 PATH ''$.username'',
               password VARCHAR2 PATH ''$.password''
             )) jt;
    
    IF V_USERNAME IS NULL OR V_PASSWORD IS NULL THEN
        :success := ''false'';
        :message := ''Usuario y contraseña son requeridos'';
        :user_json := NULL;
        :token := NULL;
        RETURN;
    END IF;
    
    -- Buscar usuario (patrón similar a SATOR)
    SELECT 
        u.US_IDUSUARIO_PK,
        u.US_NOMBRE,
        u.US_CORREO,
        u.US_USUARIO,
        u.RL_IDROL_FK,
        NVL(r.RL_NOMBRE, ''SIN_ROL'')
    INTO
        V_USER_ID,
        V_USER_NOMBRE,
        V_USER_CORREO,
        V_USER_USUARIO,
        V_ROL_ID,
        V_ROL_NOMBRE
    FROM VMS_USUARIO u
    LEFT JOIN VMS_ROL r ON u.RL_IDROL_FK = r.RL_IDROL_PK
    WHERE UPPER(u.US_USUARIO) = UPPER(V_USERNAME)
      AND u.US_CONTRASENA = (SELECT STANDARD_HASH(V_PASSWORD, ''MD5'') AS PWD FROM DUAL)
      AND u.US_ACTIVO = ''SI''
      AND ROWNUM = 1;
    
    -- Generar token (simple, sin función)
    V_STRING := V_USER_ID || ''_'' || TO_CHAR(SYSDATE, ''YYYYMMDDHH24MISS'') || ''_'' || DBMS_RANDOM.STRING(''X'', 16);
    SELECT SUBSTR(STANDARD_HASH(V_STRING, ''MD5''), 1, 32) INTO V_TOKEN FROM DUAL;
    SELECT SEQ_VMS_TOKEN_API.NEXTVAL INTO V_TOKEN_ID FROM DUAL;
    
    UPDATE VMS_TOKEN_API SET TA_ACTIVO = ''NO'' WHERE US_IDUSUARIO_FK = V_USER_ID AND TA_ACTIVO = ''SI'';
    
    INSERT INTO VMS_TOKEN_API (TA_IDTOKEN_PK, US_IDUSUARIO_FK, TA_TOKEN, TA_FECHA_CREACION, TA_FECHA_EXPIRACION, TA_ACTIVO)
    VALUES (V_TOKEN_ID, V_USER_ID, V_TOKEN, SYSDATE, SYSDATE + 1, ''SI'');
    
    COMMIT;
    
    :success := ''true'';
    :message := ''Autenticación exitosa'';
    :user_json := ''{"US_IDUSUARIO_PK":'' || V_USER_ID || 
                  '',"US_NOMBRE":"'' || REPLACE(V_USER_NOMBRE, ''"'', ''\"'') || 
                  ''","US_CORREO":"'' || REPLACE(V_USER_CORREO, ''"'', ''\"'') || 
                  ''","US_USUARIO":"'' || REPLACE(V_USER_USUARIO, ''"'', ''\"'') || 
                  ''","RL_IDROL_FK":'' || V_ROL_ID || 
                  '',"RL_NOMBRE":"'' || REPLACE(V_ROL_NOMBRE, ''"'', ''\"'') || ''"}'';
    :token := V_TOKEN;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        :success := ''false'';
        :message := ''Credenciales inválidas o usuario inactivo'';
        :user_json := NULL;
        :token := NULL;
    WHEN OTHERS THEN
        :success := ''false'';
        :message := ''Error en autenticación: '' || SUBSTR(SQLERRM, 1, 200);
        :user_json := NULL;
        :token := NULL;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/login',
      p_method             => 'POST',
      p_name               => 'success',
      p_bind_variable_name => 'success',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/login',
      p_method             => 'POST',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/login',
      p_method             => 'POST',
      p_name               => 'user_json',
      p_bind_variable_name => 'user_json',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/login',
      p_method             => 'POST',
      p_name               => 'token',
      p_bind_variable_name => 'token',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'vams/',
      p_pattern        => 'auth/login/:username/:password',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'auth/login/:username/:password',
      p_method         => 'GET',
      p_source_type    => 'json/query;type=single',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT 
    CASE 
        WHEN V_USER_ID > 0 THEN ''true''
        ELSE ''false''
    END AS "success",
    CASE 
        WHEN V_USER_ID > 0 THEN ''Autenticación exitosa''
        ELSE ''Credenciales inválidas o usuario inactivo''
    END AS "message",
    CASE 
        WHEN V_USER_ID > 0 THEN V_USER_DATA
        ELSE NULL
    END AS "user"
FROM (
    SELECT 
        VMS_AUTENTICAR_USUARIO(:username, :password) AS V_USER_ID,
        (SELECT JSON_OBJECT(
            ''US_IDUSUARIO_PK'' VALUE u.US_IDUSUARIO_PK,
            ''US_NOMBRE'' VALUE u.US_NOMBRE,
            ''US_CORREO'' VALUE u.US_CORREO,
            ''US_USUARIO'' VALUE u.US_USUARIO,
            ''RL_IDROL_FK'' VALUE u.RL_IDROL_FK,
            ''RL_NOMBRE'' VALUE NVL(r.RL_NOMBRE, ''SIN_ROL'')
        )
        FROM VMS_USUARIO u
        LEFT JOIN VMS_ROL r ON u.RL_IDROL_FK = r.RL_IDROL_PK
        WHERE UPPER(u.US_USUARIO) = UPPER(:username)
          AND u.US_CONTRASENA = STANDARD_HASH(:password, ''MD5'')
          AND u.US_ACTIVO = ''SI''
          AND ROWNUM = 1) AS V_USER_DATA
    FROM DUAL
)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/login/:username/:password',
      p_method             => 'GET',
      p_name               => 'username',
      p_bind_variable_name => 'username',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/login/:username/:password',
      p_method             => 'GET',
      p_name               => 'password',
      p_bind_variable_name => 'password',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'vams/',
      p_pattern        => 'auth/validate',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'auth/validate',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  V_TOKEN VARCHAR2(32);
  V_USER_ID NUMBER;
BEGIN
    -- Obtener token del header
    V_TOKEN := :x_api_token;
    
    IF V_TOKEN IS NULL THEN
        :success := ''false'';
        :message := ''Token no proporcionado'';
        :user_id := 0;
        RETURN;
    END IF;
    
    -- Validar token
    V_USER_ID := VMS_VALIDAR_TOKEN(V_TOKEN);
    
    IF V_USER_ID > 0 THEN
        :success := ''true'';
        :message := ''Token válido'';
        :user_id := V_USER_ID;
    ELSE
        :success := ''false'';
        :message := ''Token inválido o expirado'';
        :user_id := 0;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        :success := ''false'';
        :message := ''Error al validar token: '' || SUBSTR(SQLERRM, 1, 200);
        :user_id := 0;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/validate',
      p_method             => 'GET',
      p_name               => 'X-API-Token',
      p_bind_variable_name => 'x_api_token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/validate',
      p_method             => 'GET',
      p_name               => 'success',
      p_bind_variable_name => 'success',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/validate',
      p_method             => 'GET',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'auth/validate',
      p_method             => 'GET',
      p_name               => 'user_id',
      p_bind_variable_name => 'user_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  V_TOKEN VARCHAR2(32);
  V_USER_ID NUMBER;
  V_RESULT_JSON CLOB;
BEGIN
    -- Obtener token del header
    V_TOKEN := :x_api_token;
    
    IF V_TOKEN IS NULL THEN
        :success := ''false'';
        :message := ''Token no proporcionado'';
        :result_json := NULL;
        RETURN;
    END IF;
    
    -- Validar token
    V_USER_ID := VMS_VALIDAR_TOKEN(V_TOKEN);
    
    IF V_USER_ID = 0 THEN
        :success := ''false'';
        :message := ''Token inválido o expirado'';
        :result_json := NULL;
        RETURN;
    END IF;
    
    -- Si el token es válido, devolver los proyectos
    SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
            ''PR_IDPROYECTO_PK'' VALUE PR_IDPROYECTO_PK,
            ''PR_NOMBRE'' VALUE PR_NOMBRE,
            ''PR_UBICACION'' VALUE PR_UBICACION,
            ''PR_FOTO_PORTADA_URL'' VALUE PR_FOTO_PORTADA_URL,
            ''PR_FECHA_INICIO'' VALUE TO_CHAR(PR_FECHA_INICIO, ''YYYY-MM-DD''),
            ''PR_FECHA_FIN'' VALUE TO_CHAR(PR_FECHA_FIN, ''YYYY-MM-DD''),
            ''PR_ACTIVO'' VALUE PR_ACTIVO,
            ''TOTAL_ACTIVOS'' VALUE NVL(TOTAL_ACTIVOS, 0),
            ''TOTAL_CATEGORIAS'' VALUE NVL(TOTAL_CATEGORIAS, 0),
            ''ULTIMA_ACTUALIZACION'' VALUE TO_CHAR(ULTIMA_ACTUALIZACION, ''YYYY-MM-DD HH24:MI:SS'')
        )
    )
    INTO V_RESULT_JSON
    FROM V_PROYECTO_RESUMEN
    ORDER BY PR_FECHA_INICIO DESC, PR_NOMBRE;
    
    :success := ''true'';
    :message := ''OK'';
    :result_json := V_RESULT_JSON;

EXCEPTION
    WHEN OTHERS THEN
        :success := ''false'';
        :message := ''Error al obtener proyectos: '' || SUBSTR(SQLERRM, 1, 200);
        :result_json := NULL;
END;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  L_PO  BLOB := :body;
  V_NOMBRE VARCHAR2(200);
  V_DESCRIPCION VARCHAR2(500);
  V_UBICACION VARCHAR2(200);
  V_FECHA_INICIO DATE;
  V_FECHA_FIN DATE;
  V_FOTO_PORTADA_URL VARCHAR2(500);
  V_PROYECTO_ID NUMBER;
BEGIN
    -- Extraer datos del JSON
    SELECT 
        jt.PR_NOMBRE,
        jt.PR_DESCRIPCION,
        jt.PR_UBICACION,
        TO_DATE(jt.PR_FECHA_INICIO, ''YYYY-MM-DD''),
        TO_DATE(jt.PR_FECHA_FIN, ''YYYY-MM-DD''),
        jt.PR_FOTO_PORTADA_URL
    INTO 
        V_NOMBRE,
        V_DESCRIPCION,
        V_UBICACION,
        V_FECHA_INICIO,
        V_FECHA_FIN,
        V_FOTO_PORTADA_URL
    FROM JSON_TABLE(L_PO FORMAT JSON, ''$''
             COLUMNS (
               PR_NOMBRE VARCHAR2(200) PATH ''$.PR_NOMBRE'',
               PR_DESCRIPCION VARCHAR2(500) PATH ''$.PR_DESCRIPCION'',
               PR_UBICACION VARCHAR2(200) PATH ''$.PR_UBICACION'',
               PR_FECHA_INICIO VARCHAR2(10) PATH ''$.PR_FECHA_INICIO'',
               PR_FECHA_FIN VARCHAR2(10) PATH ''$.PR_FECHA_FIN'',
               PR_FOTO_PORTADA_URL VARCHAR2(500) PATH ''$.PR_FOTO_PORTADA_URL''
             )) jt;
    
    IF V_NOMBRE IS NULL OR TRIM(V_NOMBRE) = '''' THEN
        :success := ''false'';
        :message := ''El nombre del proyecto es requerido'';
        :proyecto_id := 0;
        RETURN;
    END IF;
    
    -- Obtener nuevo ID
    SELECT SEQ_VMS_PROYECTO.NEXTVAL INTO V_PROYECTO_ID FROM DUAL;
    
    -- Insertar proyecto
    INSERT INTO VMS_PROYECTO (
        PR_IDPROYECTO_PK,
        PR_NOMBRE,
        PR_DESCRIPCION,
        PR_UBICACION,
        PR_FECHA_INICIO,
        PR_FECHA_FIN,
        PR_FOTO_PORTADA_URL,
        PR_ACTIVO
    ) VALUES (
        V_PROYECTO_ID,
        V_NOMBRE,
        V_DESCRIPCION,
        V_UBICACION,
        V_FECHA_INICIO,
        V_FECHA_FIN,
        V_FOTO_PORTADA_URL,
        ''SI''
    );
    
    COMMIT;
    
    :success := ''true'';
    :message := ''Proyecto creado exitosamente'';
    :proyecto_id := V_PROYECTO_ID;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :success := ''false'';
        :message := ''Error al crear proyecto: '' || SUBSTR(SQLERRM, 1, 200);
        :proyecto_id := 0;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos',
      p_method             => 'POST',
      p_name               => 'success',
      p_bind_variable_name => 'success',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos',
      p_method             => 'POST',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos',
      p_method             => 'GET',
      p_name               => 'X-API-Token',
      p_bind_variable_name => 'x_api_token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos',
      p_method             => 'GET',
      p_name               => 'success',
      p_bind_variable_name => 'success',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos',
      p_method             => 'GET',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos',
      p_method             => 'GET',
      p_name               => 'result_json',
      p_bind_variable_name => 'result_json',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos',
      p_method             => 'POST',
      p_name               => 'proyecto_id',
      p_bind_variable_name => 'proyecto_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos/:proyecto_id/activos',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos/:proyecto_id/activos',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  V_TOKEN VARCHAR2(32);
  V_USER_ID NUMBER;
  V_PROYECTO_ID NUMBER;
  V_RESULT_JSON CLOB;
BEGIN
    -- Obtener proyecto_id del URI
    V_PROYECTO_ID := :proyecto_id;
    
    -- Obtener token del header
    V_TOKEN := :x_api_token;
    
    IF V_TOKEN IS NULL THEN
        :success := ''false'';
        :message := ''Token no proporcionado'';
        :result_json := NULL;
        RETURN;
    END IF;
    
    -- Validar token
    V_USER_ID := VMS_VALIDAR_TOKEN(V_TOKEN);
    
    IF V_USER_ID = 0 THEN
        :success := ''false'';
        :message := ''Token inválido o expirado'';
        :result_json := NULL;
        RETURN;
    END IF;
    
    -- Si el token es válido, devolver los activos
    SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
            ''av_idactivo_pk'' VALUE AV_IDACTIVO_PK,
            ''pr_idproyecto_fk'' VALUE PR_IDPROYECTO_FK,
            ''ct_idcategoria_fk'' VALUE CT_IDCATEGORIA_FK,
            ''av_nombre'' VALUE AV_NOMBRE,
            ''av_descripcion'' VALUE AV_DESCRIPCION,
            ''av_url'' VALUE AV_URL,
            ''av_fecha_captura'' VALUE TO_CHAR(AV_FECHA_CAPTURA, ''YYYY-MM-DD''),
            ''av_fecha_carga'' VALUE TO_CHAR(AV_FECHA_CARGA, ''YYYY-MM-DD HH24:MI:SS'')
        )
    )
    INTO V_RESULT_JSON
    FROM VMS_ACTIVO_VISUAL
    WHERE PR_IDPROYECTO_FK = V_PROYECTO_ID
      AND AV_ACTIVO = ''SI''
      AND AV_FECHA_CAPTURA IS NOT NULL
    ORDER BY AV_FECHA_CAPTURA DESC, AV_FECHA_CARGA DESC;
    
    :success := ''true'';
    :message := ''OK'';
    :result_json := V_RESULT_JSON;

EXCEPTION
    WHEN OTHERS THEN
        :success := ''false'';
        :message := ''Error al obtener activos: '' || SUBSTR(SQLERRM, 1, 200);
        :result_json := NULL;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'GET',
      p_name               => 'X-API-Token',
      p_bind_variable_name => 'x_api_token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'GET',
      p_name               => 'proyecto_id',
      p_bind_variable_name => 'proyecto_id',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'GET',
      p_name               => 'success',
      p_bind_variable_name => 'success',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'GET',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'GET',
      p_name               => 'result_json',
      p_bind_variable_name => 'result_json',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos/:proyecto_id/activos',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  L_PO  BLOB := :body;
  V_PROYECTO_ID NUMBER;
  V_NOMBRE VARCHAR2(200);
  V_DESCRIPCION VARCHAR2(1000);
  V_URL VARCHAR2(500);
  V_FECHA_CAPTURA DATE;
  V_FILENAME VARCHAR2(256);
  V_MIMETYPE VARCHAR2(256);
  V_TAMANIO NUMBER;
  V_ACTIVO_ID NUMBER;
  V_USER_ID NUMBER;
  V_CATEGORIA_ID NUMBER;
  V_CATEGORIA_COUNT NUMBER;
BEGIN
    -- Obtener proyecto_id del URI
    V_PROYECTO_ID := :proyecto_id;
    
    -- Obtener user_id del token
    V_USER_ID := VMS_VALIDAR_TOKEN(:x_api_token);
    
    IF V_USER_ID = 0 THEN
        :success := ''false'';
        :message := ''Token inválido o expirado'';
        :activo_id := 0;
        RETURN;
    END IF;
    
    -- Extraer datos del JSON
    SELECT 
        jt.AV_NOMBRE,
        jt.AV_DESCRIPCION,
        jt.AV_URL,
        TO_DATE(jt.AV_FECHA_CAPTURA, ''YYYY-MM-DD''),
        jt.AV_FILENAME,
        jt.AV_MIMETYPE,
        jt.AV_TAMANIO,
        jt.CT_IDCATEGORIA_FK
    INTO 
        V_NOMBRE,
        V_DESCRIPCION,
        V_URL,
        V_FECHA_CAPTURA,
        V_FILENAME,
        V_MIMETYPE,
        V_TAMANIO,
        V_CATEGORIA_ID
    FROM JSON_TABLE(L_PO FORMAT JSON, ''$''
             COLUMNS (
               AV_NOMBRE VARCHAR2(200) PATH ''$.AV_NOMBRE'',
               AV_DESCRIPCION VARCHAR2(1000) PATH ''$.AV_DESCRIPCION'',
               AV_URL VARCHAR2(500) PATH ''$.AV_URL'',
               AV_FECHA_CAPTURA VARCHAR2(10) PATH ''$.AV_FECHA_CAPTURA'',
               AV_FILENAME VARCHAR2(256) PATH ''$.AV_FILENAME'',
               AV_MIMETYPE VARCHAR2(256) PATH ''$.AV_MIMETYPE'',
               AV_TAMANIO NUMBER PATH ''$.AV_TAMANIO'',
               CT_IDCATEGORIA_FK NUMBER PATH ''$.CT_IDCATEGORIA_FK''
             )) jt;
    
    -- Si no se proporciona categoría, obtener la primera del proyecto o crear una por defecto
    IF V_CATEGORIA_ID IS NULL THEN
        SELECT MIN(CT_IDCATEGORIA_PK) INTO V_CATEGORIA_ID
        FROM VMS_CATEGORIA
        WHERE PR_IDPROYECTO_FK = V_PROYECTO_ID
          AND CT_ACTIVO = ''SI''
          AND ROWNUM = 1;
        
        -- Si no hay categoría, crear una por defecto
        IF V_CATEGORIA_ID IS NULL THEN
            SELECT SEQ_VMS_CATEGORIA.NEXTVAL INTO V_CATEGORIA_ID FROM DUAL;
            INSERT INTO VMS_CATEGORIA (
                CT_IDCATEGORIA_PK,
                PR_IDPROYECTO_FK,
                CT_NOMBRE,
                CT_DESCRIPCION,
                CT_ICONO,
                CT_ACTIVO
            ) VALUES (
                V_CATEGORIA_ID,
                V_PROYECTO_ID,
                ''General'',
                ''Categoría por defecto'',
                ''folder'',
                ''SI''
            );
        END IF;
    ELSE
        -- Validar que la categoría pertenece al proyecto
        SELECT COUNT(*) INTO V_CATEGORIA_COUNT
        FROM VMS_CATEGORIA
        WHERE CT_IDCATEGORIA_PK = V_CATEGORIA_ID
          AND PR_IDPROYECTO_FK = V_PROYECTO_ID
          AND CT_ACTIVO = ''SI'';
        
        IF V_CATEGORIA_COUNT = 0 THEN
            :success := ''false'';
            :message := ''La categoría especificada no existe o no pertenece al proyecto'';
            :activo_id := 0;
            RETURN;
        END IF;
    END IF;
    
    IF V_URL IS NULL OR V_FECHA_CAPTURA IS NULL THEN
        :success := ''false'';
        :message := ''URL y fecha de captura son requeridos'';
        :activo_id := 0;
        RETURN;
    END IF;
    
    -- Obtener nuevo ID
    SELECT SEQ_VMS_ACTIVO_VISUAL.NEXTVAL INTO V_ACTIVO_ID FROM DUAL;
    
    -- Insertar activo visual
    INSERT INTO VMS_ACTIVO_VISUAL (
        AV_IDACTIVO_PK,
        PR_IDPROYECTO_FK,
        CT_IDCATEGORIA_FK,
        US_IDUSUARIO_FK,
        AV_NOMBRE,
        AV_DESCRIPCION,
        AV_URL,
        AV_FILENAME,
        AV_MIMETYPE,
        AV_TAMANIO,
        AV_FECHA_CAPTURA,
        AV_ACTIVO
    ) VALUES (
        V_ACTIVO_ID,
        V_PROYECTO_ID,
        V_CATEGORIA_ID,
        V_USER_ID,
        V_NOMBRE,
        V_DESCRIPCION,
        V_URL,
        V_FILENAME,
        V_MIMETYPE,
        V_TAMANIO,
        V_FECHA_CAPTURA,
        ''SI''
    );
    
    COMMIT;
    
    :success := ''true'';
    :message := ''Activo visual creado exitosamente'';
    :activo_id := V_ACTIVO_ID;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :success := ''false'';
        :message := ''Error al crear activo visual: '' || SUBSTR(SQLERRM, 1, 200);
        :activo_id := 0;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'POST',
      p_name               => 'X-API-Token',
      p_bind_variable_name => 'x_api_token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'POST',
      p_name               => 'proyecto_id',
      p_bind_variable_name => 'proyecto_id',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'POST',
      p_name               => 'success',
      p_bind_variable_name => 'success',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'POST',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/activos',
      p_method             => 'POST',
      p_name               => 'activo_id',
      p_bind_variable_name => 'activo_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  -- ===================================================
  -- ENDPOINTS DE CATEGORÍAS
  -- ===================================================

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos/:proyecto_id/categorias',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos/:proyecto_id/categorias',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  V_TOKEN VARCHAR2(32);
  V_USER_ID NUMBER;
  V_PROYECTO_ID NUMBER;
  V_RESULT_JSON CLOB;
BEGIN
    -- Obtener proyecto_id del URI
    V_PROYECTO_ID := :proyecto_id;
    
    -- Obtener token del header
    V_TOKEN := :x_api_token;
    
    IF V_TOKEN IS NULL THEN
        :success := ''false'';
        :message := ''Token no proporcionado'';
        :result_json := NULL;
        RETURN;
    END IF;
    
    -- Validar token
    V_USER_ID := VMS_VALIDAR_TOKEN(V_TOKEN);
    
    IF V_USER_ID = 0 THEN
        :success := ''false'';
        :message := ''Token inválido o expirado'';
        :result_json := NULL;
        RETURN;
    END IF;
    
    -- Si el token es válido, devolver las categorías
    SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
            ''CT_IDCATEGORIA_PK'' VALUE CT_IDCATEGORIA_PK,
            ''PR_IDPROYECTO_FK'' VALUE PR_IDPROYECTO_FK,
            ''CT_NOMBRE'' VALUE CT_NOMBRE,
            ''CT_DESCRIPCION'' VALUE CT_DESCRIPCION,
            ''CT_ICONO'' VALUE CT_ICONO,
            ''CT_COLOR'' VALUE CT_COLOR,
            ''CT_ORDEN'' VALUE CT_ORDEN,
            ''CT_ACTIVO'' VALUE CT_ACTIVO
        )
    )
    INTO V_RESULT_JSON
    FROM VMS_CATEGORIA
    WHERE PR_IDPROYECTO_FK = V_PROYECTO_ID
      AND CT_ACTIVO = ''SI''
    ORDER BY CT_ORDEN, CT_NOMBRE;
    
    :success := ''true'';
    :message := ''OK'';
    :result_json := V_RESULT_JSON;

EXCEPTION
    WHEN OTHERS THEN
        :success := ''false'';
        :message := ''Error al obtener categorías: '' || SUBSTR(SQLERRM, 1, 200);
        :result_json := NULL;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'GET',
      p_name               => 'X-API-Token',
      p_bind_variable_name => 'x_api_token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'GET',
      p_name               => 'proyecto_id',
      p_bind_variable_name => 'proyecto_id',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'GET',
      p_name               => 'success',
      p_bind_variable_name => 'success',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'GET',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'GET',
      p_name               => 'result_json',
      p_bind_variable_name => 'result_json',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vams/',
      p_pattern        => 'proyectos/:proyecto_id/categorias',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  L_PO  BLOB := :body;
  V_PROYECTO_ID NUMBER;
  V_NOMBRE VARCHAR2(100);
  V_DESCRIPCION VARCHAR2(500);
  V_ICONO VARCHAR2(50);
  V_COLOR VARCHAR2(20);
  V_ORDEN NUMBER;
  V_CATEGORIA_ID NUMBER;
  V_USER_ID NUMBER;
BEGIN
    -- Obtener proyecto_id del URI
    V_PROYECTO_ID := :proyecto_id;
    
    -- Obtener user_id del token
    V_USER_ID := VMS_VALIDAR_TOKEN(:x_api_token);
    
    IF V_USER_ID = 0 THEN
        :success := ''false'';
        :message := ''Token inválido o expirado'';
        :categoria_id := 0;
        RETURN;
    END IF;
    
    -- Extraer datos del JSON
    SELECT 
        jt.CT_NOMBRE,
        jt.CT_DESCRIPCION,
        jt.CT_ICONO,
        jt.CT_COLOR,
        jt.CT_ORDEN
    INTO 
        V_NOMBRE,
        V_DESCRIPCION,
        V_ICONO,
        V_COLOR,
        V_ORDEN
    FROM JSON_TABLE(L_PO FORMAT JSON, ''$''
             COLUMNS (
               CT_NOMBRE VARCHAR2(100) PATH ''$.CT_NOMBRE'',
               CT_DESCRIPCION VARCHAR2(500) PATH ''$.CT_DESCRIPCION'',
               CT_ICONO VARCHAR2(50) PATH ''$.CT_ICONO'',
               CT_COLOR VARCHAR2(20) PATH ''$.CT_COLOR'',
               CT_ORDEN NUMBER PATH ''$.CT_ORDEN''
             )) jt;
    
    IF V_NOMBRE IS NULL OR TRIM(V_NOMBRE) = '''' THEN
        :success := ''false'';
        :message := ''El nombre de la categoría es requerido'';
        :categoria_id := 0;
        RETURN;
    END IF;
    
    -- Si no se proporciona orden, usar el máximo + 1
    IF V_ORDEN IS NULL THEN
        SELECT NVL(MAX(CT_ORDEN), 0) + 1 INTO V_ORDEN
        FROM VMS_CATEGORIA
        WHERE PR_IDPROYECTO_FK = V_PROYECTO_ID;
    END IF;
    
    -- Si no se proporciona icono, usar uno por defecto
    IF V_ICONO IS NULL OR TRIM(V_ICONO) = '''' THEN
        V_ICONO := ''folder'';
    END IF;
    
    -- Obtener nuevo ID
    SELECT SEQ_VMS_CATEGORIA.NEXTVAL INTO V_CATEGORIA_ID FROM DUAL;
    
    -- Insertar categoría
    INSERT INTO VMS_CATEGORIA (
        CT_IDCATEGORIA_PK,
        PR_IDPROYECTO_FK,
        CT_NOMBRE,
        CT_DESCRIPCION,
        CT_ICONO,
        CT_COLOR,
        CT_ORDEN,
        CT_ACTIVO
    ) VALUES (
        V_CATEGORIA_ID,
        V_PROYECTO_ID,
        V_NOMBRE,
        V_DESCRIPCION,
        V_ICONO,
        V_COLOR,
        V_ORDEN,
        ''SI''
    );
    
    COMMIT;
    
    :success := ''true'';
    :message := ''Categoría creada exitosamente'';
    :categoria_id := V_CATEGORIA_ID;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :success := ''false'';
        :message := ''Error al crear categoría: '' || SUBSTR(SQLERRM, 1, 200);
        :categoria_id := 0;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'POST',
      p_name               => 'X-API-Token',
      p_bind_variable_name => 'x_api_token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'POST',
      p_name               => 'proyecto_id',
      p_bind_variable_name => 'proyecto_id',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'POST',
      p_name               => 'success',
      p_bind_variable_name => 'success',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'POST',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'vams/',
      p_pattern            => 'proyectos/:proyecto_id/categorias',
      p_method             => 'POST',
      p_name               => 'categoria_id',
      p_bind_variable_name => 'categoria_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

    
        
COMMIT;

END;
